# Conda Environment Setup ----
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f conda_environment_setup/environment_setup.yaml
#    conda env update --file conda_environment_setup/environment_setup.yaml --prune
#    conda env export --name python_automation > envname.yml
#    conda env remove --name python_automation
#    conda activate python_automation
#    conda deactivate
#    conda env list

name: python_automation
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - pip
  - pip:
      # Core Data
      - numpy==1.19.5
      - pandas==1.3.3
      - pandas_datareader==0.10.0
      - SciPy==1.5.4
      - xlrd==1.2.0

      # EDA
      - pandas-profiling
      
      # Modeling & Machine Learning
      - scikit-learn==0.23.2
      - xgboost==0.90
      - lightgbm==3.1.1
      - catboost==0.24.4
      - sklearn-pandas==2.0.4
      - scikit-misc==0.1.3
      - category_encoders==2.3.0
      - pycaret==2.3.4

      # Jupyter
      - jupyterlab==3.0.18
      - jupyterlab-server==2.8.0
      - ipywidgets==7.6.3
      - ipympl==0.7.0
      - jupytext
      - papermill==2.3.3

      # AWS
      - boto3==1.18.21

      # SQL
      - psycopg2==2.8.6

      # Python integration 
      - pypdf2==1.26.0
      - pikepdf==4.3.0
      - python-docx==0.8.11
      - camelot-py==0.9.0
      - ghostscript==0.7 
      - tabula-py==2.3.0

      # R Data
      - plydata==0.4.3
      - siuba==0.0.24
      - datatable==1.0.0

      # Visualization
      - matplotlib==3.3.4
      - plotnine==0.7.1
      - mizani==0.7.2
      - plotly==4.14.3
      - altair==4.1.0

      # Environment & Library Management
      - nodejs==0.1.1
      - pipreqs==0.4.10  

      # Software development
      - coverage==6.2
      - pytest==6.2.5
      - pytest-randomly==3.11.0
      - pytest-cov==3.0.0
      - cookiecutter==1.7.3
      - poetry==1.1.13

